// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoNo8oDewiMERBHssIY3pVZXK3_WqQb4I',
    appId: '1:92967198669:web:50f1c7727176b184c7ae84',
    messagingSenderId: '92967198669',
    projectId: 'firbase-scratchpad',
    authDomain: 'firbase-scratchpad.firebaseapp.com',
    storageBucket: 'firbase-scratchpad.firebasestorage.app',
    measurementId: 'G-ZQ215S26QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7-dQylI4eoMARaN2Bad1yeqvRNjTbk8',
    appId: '1:92967198669:android:6ea67af24550e1b7c7ae84',
    messagingSenderId: '92967198669',
    projectId: 'firbase-scratchpad',
    storageBucket: 'firbase-scratchpad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi5KLWUscsNn-PvGmbyHrHtQaOwPpFQ7Y',
    appId: '1:92967198669:ios:d94e9ecba84531ecc7ae84',
    messagingSenderId: '92967198669',
    projectId: 'firbase-scratchpad',
    storageBucket: 'firbase-scratchpad.firebasestorage.app',
    iosBundleId: 'com.example.firebaseScratchpad',
  );
}
